# LISTA 8 - PANDAS

## EJERCICIO 1

Crea un dataframe con 15 filas y 2 columnas. La primera columna se llamará x, la segunda y. Cada entrada será un número aleatorio (puedes usar random.normal() de la librería numpy). Guarda el dataframe en una variable llamada points.

In [33]:
import pandas as pd
import numpy as np
x = np.random.normal(0,1,15)
y = np.random.normal(0,2,15)
data=list(zip(x,y))
points=pd.DataFrame(data,columns=["x","y"])
print(points)

           x         y
0   0.751587  1.519182
1   1.863283  2.318782
2  -1.204862 -1.988837
3   0.516154  0.839616
4  -0.410595 -3.033201
5   0.688417  0.193621
6   1.024661 -2.836498
7  -0.289182  1.536876
8  -1.893490  5.284858
9  -0.425569  1.664663
10 -0.600376 -2.587093
11 -0.733682  0.106463
12 -0.714227 -3.670099
13 -0.551951  0.294642
14  0.684221  0.719441

## EJERCICIO 2

Del dataframe points, muestra las filas cuyo valor en la columna x sea positivo.

In [2]:
print(points[points["x"]>=0])

           x         y
0   0.606397  0.071383
1   1.213017  1.548755
3   1.173115  2.535201
4   1.287283  2.015967
6   0.807414 -0.885096
8   0.270601  2.741777
9   0.176620  2.783335
11  0.220468  2.856759
12  0.928511  1.409406
13  0.273509  2.279927
14  0.229546 -1.880784

## EJERCICIO 3

Del dataframe points, muestra las filas cuyo valor en la columna y sea negativo.

In [4]:
print(points.query('y<0'))

           x         y
2  -0.786474 -2.143186
6   0.807414 -0.885096
7  -1.556197 -1.074938
10 -1.232976 -1.522987
14  0.229546 -1.880784

## EJERCICIO 4

Del dataframe points, muestra las observaciones cuyos puntos (x, y) pertenezcan al primer cuadrante.

In [5]:
print(points.query('y>0 and x>0'))

filtro=(points["x"] >= 0) & (points["y"] >= 0)
print(points[filtro])

           x         y
0   0.606397  0.071383
1   1.213017  1.548755
3   1.173115  2.535201
4   1.287283  2.015967
8   0.270601  2.741777
9   0.176620  2.783335
11  0.220468  2.856759
12  0.928511  1.409406
13  0.273509  2.279927
           x         y
0   0.606397  0.071383
1   1.213017  1.548755
3   1.173115  2.535201
4   1.287283  2.015967
8   0.270601  2.741777
9   0.176620  2.783335
11  0.220468  2.856759
12  0.928511  1.409406
13  0.273509  2.279927

## EJERCICIO 5

Del dataframe points, muestra las observaciones de la forma: “El punto ({x}, {y}) {no/sí} pertenece al primer cuadrante”.

In [36]:
for j in points.itertuples():
    cuadrante1="no"
    if j[0]>=0 and j[1]>=0:
        cuadrante1="si"
    print("El punto ({:.2f},{:.2f}) {} pertenece al primer cuadrante".format(j[0],j[1],cuadrante1))

El punto (0.00,0.75) si pertenece al primer cuadrante
El punto (1.00,1.86) si pertenece al primer cuadrante
El punto (2.00,-1.20) no pertenece al primer cuadrante
El punto (3.00,0.52) si pertenece al primer cuadrante
El punto (4.00,-0.41) no pertenece al primer cuadrante
El punto (5.00,0.69) si pertenece al primer cuadrante
El punto (6.00,1.02) si pertenece al primer cuadrante
El punto (7.00,-0.29) no pertenece al primer cuadrante
El punto (8.00,-1.89) no pertenece al primer cuadrante
El punto (9.00,-0.43) no pertenece al primer cuadrante
El punto (10.00,-0.60) no pertenece al primer cuadrante
El punto (11.00,-0.73) no pertenece al primer cuadrante
El punto (12.00,-0.71) no pertenece al primer cuadrante
El punto (13.00,-0.55) no pertenece al primer cuadrante
El punto (14.00,0.68) si pertenece al primer cuadrante

## EJERCICIO 6

Crea un dataframe con 10 filas y 4 columnas. La primera columna se llamará word; la segunda, length; la tercera, vowels; y la última, consonants. La columna words contendrá las siguientes 10 palabras: “euro”, “diez” “algas”, “broma”, “cicuta”, “fatiga”, “nachos”, “jadeos”, “hazañas”, “boutique”. Las columnas length, vowels y consonants contendrán, respectivamente, la longitud, el total de vocales y el total de consonantes (añade las columnas calculando su valor por código). Guarda el dataframe en la variable words.

In [38]:
import pandas as pd

def contarVocales(palabra):
    numVocales=0
    palabra=palabra.lower()
    for c in palabra:
        if c in "aeiou":
            numVocales+=1
    return numVocales

def contarConsonantes(palabra):
    numConsonantes=0
    palabra=palabra.lower()
    for c in palabra:
        if c in "bcdfghjklmnñpqrstvwxyz":
            numConsonantes+=1
    return numConsonantes

palabras = ["euro", "diez", "algas", "broma", "cicuta", "fatiga", "nachos", "jadeos", "hazañas", "boutique"]
data = {"words": palabras, "length": list(map(len,palabras)), "vocals": list(map(contarVocales,palabras)), "consonants": list(map(contarConsonantes,palabras))}
words=pd.DataFrame(data)
print(words)

      words  length  vocals  consonants
0      euro       4       3           1
1      diez       4       2           2
2     algas       5       2           3
3     broma       5       2           3
4    cicuta       6       3           3
5    fatiga       6       3           3
6    nachos       6       2           4
7    jadeos       6       3           3
8   hazañas       7       3           4
9  boutique       8       5           3

## EJERCICIO 7

Muestra las 10 observaciones de words con el formato “La palabra {word} tiene {length} letras, de las cuales {vowels} son vocales y {consonants} consonantes”.

In [8]:
for obsv in words.itertuples():
    print("La palabra {} tiene {} letras, de las cuales {} son vocales y {} consonantes".format(obsv[1],obsv[2],obsv[3],obsv[4]))

La palabra euro tiene 4 letras, de las cuales 3 son vocales y 1 consonantes
La palabra diez tiene 4 letras, de las cuales 2 son vocales y 2 consonantes
La palabra algas tiene 5 letras, de las cuales 2 son vocales y 3 consonantes
La palabra broma tiene 5 letras, de las cuales 2 son vocales y 3 consonantes
La palabra cicuta tiene 6 letras, de las cuales 3 son vocales y 3 consonantes
La palabra fatiga tiene 6 letras, de las cuales 3 son vocales y 3 consonantes
La palabra nachos tiene 6 letras, de las cuales 2 son vocales y 4 consonantes
La palabra jadeos tiene 6 letras, de las cuales 3 son vocales y 3 consonantes
La palabra hazañas tiene 7 letras, de las cuales 3 son vocales y 4 consonantes
La palabra boutique tiene 8 letras, de las cuales 5 son vocales y 3 consonantes

## EJERCICIO 8

Muestra aquellas observaciones de words que tienen el mismo número de vocales y consonantes.

In [9]:
print(words.query('vocals==consonants'))

print(words[words["vocals"]==words["consonants"]])

    words  length  vocals  consonants
1    diez       4       2           2
4  cicuta       6       3           3
5  fatiga       6       3           3
7  jadeos       6       3           3
    words  length  vocals  consonants
1    diez       4       2           2
4  cicuta       6       3           3
5  fatiga       6       3           3
7  jadeos       6       3           3

## EJERCICIO 9

Investiga el método .sort_values() para ordenar las observaciones según la longitud de las palabras en orden descendente.

In [10]:
print(words.sort_values('length',ascending=False))

      words  length  vocals  consonants
9  boutique       8       5           3
8   hazañas       7       3           4
4    cicuta       6       3           3
5    fatiga       6       3           3
6    nachos       6       2           4
7    jadeos       6       3           3
2     algas       5       2           3
3     broma       5       2           3
0      euro       4       3           1
1      diez       4       2           2

## EJERCICIO 10

Convierte la columna vowels a lista y, con sorted() ordénala de mayor a menor. Investiga para ello el método .tolist().

In [11]:
numVocales=sorted(words['vocals'].tolist(),reverse=True)
print(numVocales)

[5, 3, 3, 3, 3, 3, 2, 2, 2, 2]

## EJERCICIO 11

El siguiente DataFrame contiene información de los pisos en alquiler en Murcia a fecha de 31/12/2020:
```
fotocasa_df = pd.read_csv("https://drive.google.com/uc?export=view&id=1DwvALe87aeDzTk7s6xGPDd6itJ65s4YE", index_col = 0)
```
Muestra el número de filas, columnas y valores que contiene el DataFrame cargado:

In [39]:
fotocasa_df = pd.read_csv("https://drive.google.com/uc?export=view&id=1DwvALe87aeDzTk7s6xGPDd6itJ65s4YE", index_col = 0)
# Filas:
print(f"Número de filas (1): {len(fotocasa_df)}")
print(f"Número de filas (2): {len(fotocasa_df.index)}")
print(f"Número de filas (3): {fotocasa_df.shape[0]}")
# Columnas
print(f"Número de columnas (1): {len(fotocasa_df.columns)}")
print(f"Número de columnas (2): {fotocasa_df.shape[1]}")
# Valores
print(f"Número de valores (1): {fotocasa_df.size}")
print(f"Número de valores (2): {fotocasa_df.shape[0] * fotocasa_df.shape[1]}")

Número de filas (1): 617
Número de filas (2): 617
Número de filas (3): 617
Número de columnas (1): 59
Número de columnas (2): 59
Número de valores (1): 36403
Número de valores (2): 36403

## EJERCICIO 12

Recupera los cinco primeros pisos (filas)

In [13]:
fotocasa_df.head()

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Serv. portería,Internet,Suite - con baño,Patio,Domótica,Pista de Tenis,Alarma,Mascotas,Energía Solar,Gimnasio
0,A consultar,Piso de alquiler en Centro,TRABAJADORES Y ESTUDIANTES ATENCION!!!! VIVIEN...,18 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>110</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,500 € /mes,Apartamento de alquiler en Centro,Maravilloso apartamento para entrar a vivir en...,21 Fotos,Centro,True,BREXTOM MURCIA,<span><span>1</span> hab.</span>,<span><span>1</span> baño</span>,<span><span>46</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,900 € /mes,Piso de alquiler en Doctor Marañón Centro,Se alquila estupenda vivienda recién reformada...,18 Fotos,Doctor Marañón Centro,True,ABAD SERVICIOS INMOBILIARIOS,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>169</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,750 € /mes,Piso de alquiler en Centro,Te presentamos este fabuloso apartamento situa...,30 Fotos,Centro,True,ABAD SERVICIOS INMOBILIARIOS,<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>77</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,800 € /mes,Piso de alquiler en Centro,Fantástica vivienda en alquiler ubicada muy pr...,28 Fotos,Centro,True,BREXTOM MURCIA,<span><span>3</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>104</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 13

Recupera los cinco últimos pisos:

In [14]:
fotocasa_df.tail()

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Serv. portería,Internet,Suite - con baño,Patio,Domótica,Pista de Tenis,Alarma,Mascotas,Energía Solar,Gimnasio
612,NaN,Alquiler piso en barrio dEl Carmen en El Carme...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,NaN,Alquiler apartamento en plaza san nicolas en M...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,NaN,Alquiler apartamento exclusivo apto plaza flor...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,NaN,Alquiler piso alquiler de local entresuelo en ...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,NaN,"Alquiler piso en alquiler en edificio alba, sa...",NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 14

Recupera aquellos pisos que ocupan una posición múltiplo de 100:

In [15]:
fotocasa_df[::100]

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Serv. portería,Internet,Suite - con baño,Patio,Domótica,Pista de Tenis,Alarma,Mascotas,Energía Solar,Gimnasio
0,A consultar,Piso de alquiler en Centro,TRABAJADORES Y ESTUDIANTES ATENCION!!!! VIVIEN...,18 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>110</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,540 € /mes,Piso de alquiler en C/ José Hernández - Ed Alc...,PROMOCIÓN: 1 MES DE ALQUILER GRATIS si reserva...,27 Fotos,C/ José Hernández - Ed Alcántara II - Espinardo,True,SOLVIA SERVICIOS INMOBILIARIOS S.L,<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>82</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,700 € /mes,Apartamento de alquiler en Centro,"Alquiler de apartamento en el centro, junto a ...",19 Fotos,Centro,True,BASCUÑANA INMOBILIARIA,<span><span>2</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>70</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,850 € /mes,Piso de alquiler en Juan de Borbón - La Flota,Piso completamente amueblado y cocina equipada...,13 Fotos,Juan de Borbón - La Flota,True,THE SIMPLE RENT LUXURY PROPERTIES,<span><span>3</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>90</span> m²</span>,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400,700 € /mes,Piso de alquiler en Centro,Piso completamente amueblado y cocina equipada...,10 Fotos,Centro,True,OPAU MURCIA,<span><span>2</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>45</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,550 € /mes,Piso de alquiler en Calle del Platanito Vistab...,Vivienda 4 dormitorios en Avenida de la Fama! ...,9 Fotos,Calle del Platanito Vistabella,True,LOGAR 21,<span><span>4</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>95</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,NaN,Alquiler piso exclusiva vivienda en el Centro ...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 15

Muestra el piso que se encuentra en la posición 7:

In [16]:
fotocasa_df.iloc[7]

Precio                                                        300 € /mes
Título                                  Estudio de alquiler en Barriomar
Descripción            Estudio equipado completo. Cocina con electrod...
Fotos                                                            5 Fotos
Dirección                                                      Barriomar
Inmobiliaria                                                        True
Anunciante                                                   OPAU MURCIA
Habitaciones                                                         NaN
Baños                                   <span><span>1</span> baño</span>
Superficie                               <span><span>35</span> m²</span>
Tipo de inmueble                                                 Estudio
Ascensor                                                              Sí
Amueblado                                                             Sí
Depósito                                                             NaN
Gastos de comunidad                                                  NaN
Consumo energía                                     G\n999 kW h m² / año
Emisiones                                  En trámite\n- kg CO₂ m² / año
Aire acondicionado                                                  True
Armarios                                                             NaN
Electrodomésticos                                                    NaN
Horno                                                                NaN
Lavadora                                                             NaN
Microondas                                                           NaN
Nevera                                                               NaN
Videoportero                                                         NaN
Puerta Blindada                                                      NaN
Lavadero                                                             NaN
Cocina Equipada                                                     True
Enlace                 https://www.fotocasa.es/es/alquiler/vivienda/m...
Planta                                                         1ª planta
Antigüedad                                                           NaN
Calefacción                                                          NaN
Terraza                                                              NaN
Balcón                                                              True
Orientación                                                          NaN
Estado                                                              Bien
Parking                                                              NaN
Gres Cerámica                                                        NaN
Cocina Office                                                        NaN
Trastero                                                             NaN
Agua caliente                                                        NaN
Jardín Privado                                                       NaN
Parquet                                                              NaN
Z. Comunitaria                                                       NaN
Piscina                                                              NaN
TV                                                                   NaN
Zona Deportiva                                                       NaN
Zona Infantil                                                        NaN
Piscina comunitaria                                                  NaN
Serv. portería                                                       NaN
Internet                                                             NaN
Suite - con baño                                                     NaN
Patio                                                                NaN
Domótica                                                             NaN
Pista de Tenis                                                       NaN
Alarma                                                               NaN
Mascotas                                                             NaN
Energía Solar                                                        NaN
Gimnasio                                                             NaN
Name: 7, dtype: object

## EJERCICIO 16

Muestra el piso cuyo índice vale 9:

In [17]:
fotocasa_df.loc[9]

Precio                                                      1.400 € /mes
Título                                        Piso de alquiler en Centro
Descripción            Piso de 3 dormitorios, equipados completos, la...
Fotos                                                           16 Fotos
Dirección                                                         Centro
Inmobiliaria                                                        True
Anunciante                             THE SIMPLE RENT LUXURY PROPERTIES
Habitaciones                           <span><span>3</span> habs.</span>
Baños                                  <span><span>2</span> baños</span>
Superficie                              <span><span>150</span> m²</span>
Tipo de inmueble                                                    Piso
Ascensor                                                              Sí
Amueblado                                                             Sí
Depósito                                                             NaN
Gastos de comunidad                                                   Sí
Consumo energía                                     G\n999 kW h m² / año
Emisiones                                  En trámite\n- kg CO₂ m² / año
Aire acondicionado                                                  True
Armarios                                                             NaN
Electrodomésticos                                                   True
Horno                                                                NaN
Lavadora                                                            True
Microondas                                                           NaN
Nevera                                                              True
Videoportero                                                         NaN
Puerta Blindada                                                      NaN
Lavadero                                                             NaN
Cocina Equipada                                                     True
Enlace                 https://www.fotocasa.es/es/alquiler/vivienda/m...
Planta                                                         3ª planta
Antigüedad                                                           NaN
Calefacción                                                          NaN
Terraza                                                              NaN
Balcón                                                               NaN
Orientación                                                          NaN
Estado                                                               NaN
Parking                                                      Comunitario
Gres Cerámica                                                        NaN
Cocina Office                                                        NaN
Trastero                                                             NaN
Agua caliente                                                        NaN
Jardín Privado                                                       NaN
Parquet                                                              NaN
Z. Comunitaria                                                       NaN
Piscina                                                              NaN
TV                                                                   NaN
Zona Deportiva                                                       NaN
Zona Infantil                                                        NaN
Piscina comunitaria                                                  NaN
Serv. portería                                                       NaN
Internet                                                             NaN
Suite - con baño                                                     NaN
Patio                                                                NaN
Domótica                                                             NaN
Pista de Tenis                                                       NaN
Alarma                                                               NaN
Mascotas                                                             NaN
Energía Solar                                                        NaN
Gimnasio                                                             NaN
Name: 9, dtype: object

## EJERCICIO 17

Muestra el campo Dirección de los tres primeros pisos. Utiliza para ello tanto el operador ```[]``` como ```[[]]```. ¿Qué diferencia encuentras?

In [41]:
fotocasa_df.head(3)['Dirección']

0                   Centro
1                   Centro
2    Doctor Marañón Centro
Name: Dirección, dtype: object

In [42]:
fotocasa_df.head(3)[['Dirección']]

               Dirección
0                 Centro
1                 Centro
2  Doctor Marañón Centro

## EJERCICIO 18

Muestra los campos Inmobiliaria y Tipo de inmueble de los tres últimos pisos:

In [19]:
fotocasa_df.tail(3)[["Inmobiliaria", "Tipo de inmueble"]]

     Inmobiliaria Tipo de inmueble
614          True              NaN
615          True              NaN
616          True              NaN

## EJERCICIO 19

Muestra el valor del DataFrame contenido en la posición (2,2):

In [20]:
fotocasa_df.iat[2,2]

'Se alquila estupenda vivienda recién reformada en pleno centro de Murcia junto a la Avenida Constitución . Cuenta con 4 dormitorios muy amplios, dos baños, cocina independiente amueblada con electrodomésticos y terraza acristalada. La vivienda se alquila sin muebles, .con los gastos de la comunidad incluidos en el precio, que incluye también el coste de la calefacción. El edificio cuenta con portero físico y está en zona inmejorable con todo tipo de servicios alrededor. Por expreso deseo del propietario, este inmueble lo comercializamos en exclusiva. Nuestros asesores le facilitarán toda la información que precise, por lo que le rogamos no moleste al propietario o a los vecinos. Y si usted es una agencia inmobiliaria y tiene un cliente interesado, póngase en contacto con nosotros y estaremos encantados de colaborar.'

In [43]:
fotocasa_df.iloc[2,2]

'Se alquila estupenda vivienda recién reformada en pleno centro de Murcia junto a la Avenida Constitución . Cuenta con 4 dormitorios muy amplios, dos baños, cocina independiente amueblada con electrodomésticos y terraza acristalada. La vivienda se alquila sin muebles, .con los gastos de la comunidad incluidos en el precio, que incluye también el coste de la calefacción. El edificio cuenta con portero físico y está en zona inmejorable con todo tipo de servicios alrededor. Por expreso deseo del propietario, este inmueble lo comercializamos en exclusiva. Nuestros asesores le facilitarán toda la información que precise, por lo que le rogamos no moleste al propietario o a los vecinos. Y si usted es una agencia inmobiliaria y tiene un cliente interesado, póngase en contacto con nosotros y estaremos encantados de colaborar.'

## EJERCICIO 20

Muestra el valor del DataFrame cuyo índice es 2 y cuya columna es Título:

In [21]:
fotocasa_df.at[2, "Título"]

'Piso de alquiler en Doctor Marañón Centro'

In [44]:
fotocasa_df.loc[2,"Título"]

'Piso de alquiler en Doctor Marañón Centro'

## EJERCICIO 21

Muestra los tres primeros inmuebles de Tipo de inmueble = Apartamento:

In [22]:
fotocasa_df[fotocasa_df["Tipo de inmueble"] == "Apartamento"].head(3)

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Serv. portería,Internet,Suite - con baño,Patio,Domótica,Pista de Tenis,Alarma,Mascotas,Energía Solar,Gimnasio
1,500 € /mes,Apartamento de alquiler en Centro,Maravilloso apartamento para entrar a vivir en...,21 Fotos,Centro,True,BREXTOM MURCIA,<span><span>1</span> hab.</span>,<span><span>1</span> baño</span>,<span><span>46</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,500 € /mes,Apartamento de alquiler en Espinardo,"Apartamento de 1 dormitorio,totalmente amuebla...",8 Fotos,Espinardo,True,OPAU MURCIA,<span><span>1</span> hab.</span>,<span><span>1</span> baño</span>,<span><span>40</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,400 € /mes,Apartamento de alquiler en El Carmen,"Apartamento con 1 dormitorio independiente, eq...",5 Fotos,El Carmen,True,OPAU MURCIA,<span><span>1</span> hab.</span>,<span><span>1</span> baño</span>,<span><span>33</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 22

Muestra los dos primeros inmuebles de Tipo de inmueble = Piso y que no se alquilen por inmobiliaria (Inmobiliaria = False):

In [23]:
fotocasa_df[(fotocasa_df["Tipo de inmueble"] == "Piso") & (fotocasa_df["Inmobiliaria"] == False)].head(2)

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Serv. portería,Internet,Suite - con baño,Patio,Domótica,Pista de Tenis,Alarma,Mascotas,Energía Solar,Gimnasio
36,550 € /mes,"Piso de alquiler en Calle Joaquín Báguena, 10 ...","Alquilo piso centrico y muy cuidado, con parqu...",15 Fotos,"Calle Joaquín Báguena, 10 Centro",False,"<span class=""re-ContactDetail-particularLabel""...",<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>53</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,560 € /mes,"Piso de alquiler en Avenida del Palmar, 44 Ron...",RONDA SUR (Zona innovadora)\nParticular (Sin c...,20 Fotos,"Avenida del Palmar, 44 Ronda Sur",False,"<span class=""re-ContactDetail-particularLabel""...",<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>78</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 23

Las columnas Domótica, Pista de Tenis, Alarma, Mascotas, Energía Solar y Gimnasio no contienen apenas valores definidos. Elimínalas del DataFrame y almacena el resultado en fotocasa1_df:

In [47]:
fotocasa1_df = fotocasa_df.drop(['Pista de Tenis', 'Alarma', 'Mascotas', 'Energía Solar', 'Gimnasio'], axis=1)
fotocasa1_df.iloc[1]

Precio                                                        500 € /mes
Título                                 Apartamento de alquiler en Centro
Descripción            Maravilloso apartamento para entrar a vivir en...
Fotos                                                           21 Fotos
Dirección                                                         Centro
Inmobiliaria                                                        True
Anunciante                                                BREXTOM MURCIA
Habitaciones                            <span><span>1</span> hab.</span>
Baños                                   <span><span>1</span> baño</span>
Superficie                               <span><span>46</span> m²</span>
Tipo de inmueble                                             Apartamento
Ascensor                                                              Sí
Amueblado                                                            NaN
Depósito                                                             NaN
Gastos de comunidad                                                  NaN
Consumo energía                                     G\n999 kW h m² / año
Emisiones                                  En trámite\n- kg CO₂ m² / año
Aire acondicionado                                                  True
Armarios                                                            True
Electrodomésticos                                                   True
Horno                                                                NaN
Lavadora                                                             NaN
Microondas                                                           NaN
Nevera                                                               NaN
Videoportero                                                         NaN
Puerta Blindada                                                      NaN
Lavadero                                                             NaN
Cocina Equipada                                                     True
Enlace                 https://www.fotocasa.es/es/alquiler/vivienda/m...
Planta                                                         2ª planta
Antigüedad                                                  30 a 50 años
Calefacción                                                         True
Terraza                                                              NaN
Balcón                                                               NaN
Orientación                                                          NaN
Estado                                                               NaN
Parking                                                              NaN
Gres Cerámica                                                        NaN
Cocina Office                                                        NaN
Trastero                                                             NaN
Agua caliente                                                        NaN
Jardín Privado                                                       NaN
Parquet                                                              NaN
Z. Comunitaria                                                       NaN
Piscina                                                              NaN
TV                                                                   NaN
Zona Deportiva                                                       NaN
Zona Infantil                                                        NaN
Piscina comunitaria                                                  NaN
Serv. portería                                                       NaN
Internet                                                             NaN
Suite - con baño                                                     NaN
Patio                                                                NaN
Domótica                                                             NaN
Name: 1, dtype: object

## EJERCICIO 24

Renombra a continuación la columna Tipo de inmueble de fotocasa1_df por Tipo. Asigna el resultado a la variable fotocasa2_df:

In [49]:
fotocasa2_df = fotocasa1_df.rename(columns={'Tipo de inmueble': 'Tipo'})
fotocasa2_df.iloc[1]

Precio                                                        500 € /mes
Título                                 Apartamento de alquiler en Centro
Descripción            Maravilloso apartamento para entrar a vivir en...
Fotos                                                           21 Fotos
Dirección                                                         Centro
Inmobiliaria                                                        True
Anunciante                                                BREXTOM MURCIA
Habitaciones                            <span><span>1</span> hab.</span>
Baños                                   <span><span>1</span> baño</span>
Superficie                               <span><span>46</span> m²</span>
Tipo                                                         Apartamento
Ascensor                                                              Sí
Amueblado                                                            NaN
Depósito                                                             NaN
Gastos de comunidad                                                  NaN
Consumo energía                                     G\n999 kW h m² / año
Emisiones                                  En trámite\n- kg CO₂ m² / año
Aire acondicionado                                                  True
Armarios                                                            True
Electrodomésticos                                                   True
Horno                                                                NaN
Lavadora                                                             NaN
Microondas                                                           NaN
Nevera                                                               NaN
Videoportero                                                         NaN
Puerta Blindada                                                      NaN
Lavadero                                                             NaN
Cocina Equipada                                                     True
Enlace                 https://www.fotocasa.es/es/alquiler/vivienda/m...
Planta                                                         2ª planta
Antigüedad                                                  30 a 50 años
Calefacción                                                         True
Terraza                                                              NaN
Balcón                                                               NaN
Orientación                                                          NaN
Estado                                                               NaN
Parking                                                              NaN
Gres Cerámica                                                        NaN
Cocina Office                                                        NaN
Trastero                                                             NaN
Agua caliente                                                        NaN
Jardín Privado                                                       NaN
Parquet                                                              NaN
Z. Comunitaria                                                       NaN
Piscina                                                              NaN
TV                                                                   NaN
Zona Deportiva                                                       NaN
Zona Infantil                                                        NaN
Piscina comunitaria                                                  NaN
Serv. portería                                                       NaN
Internet                                                             NaN
Suite - con baño                                                     NaN
Patio                                                                NaN
Domótica                                                             NaN
Name: 1, dtype: object

## EJERCICIO 25

Elimina del DataFrame contenido en fotocasa2_df los alquileres de la posición 597 y 598. Asigna el resultado a fotocasa3_df:

In [26]:
fotocasa3_df = fotocasa2_df.drop([597,598])
fotocasa3_df.tail(30)

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Piscina,TV,Zona Deportiva,Zona Infantil,Piscina comunitaria,Serv. portería,Internet,Suite - con baño,Patio,Domótica
585,A consultar,Piso de alquiler en Centro,"ATENCION ESTUDIANTE PISO CERCANO A LA MERCED, ...",9 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>3</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>100</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,750 € /mes,Apartamento de alquiler en Juan Carlos I,"MAGNIFICO APARTAMENTO EN AVENIDA DE EUROPA, DO...",14 Fotos,Juan Carlos I,True,DPTO. COMERCIAL PISOSMUR,<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>70</span> m²</span>,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,900 € /mes,Piso de alquiler en Plaza Plaza Preciosa Centro,ATENCIÓN ESTUDIANTES!!!! SE ALQUILA MAGNIFICA ...,16 Fotos,Plaza Plaza Preciosa Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>120</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
588,660 € /mes,Piso de alquiler en Juan Carlos I,ATENCIÓN ESTUDIANTES VIVIENDA REFORMADA EN VIS...,9 Fotos,Juan Carlos I,True,DPTO. COMERCIAL PISOSMUR,<span><span>3</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>80</span> m²</span>,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,600 € /mes,Piso de alquiler en Calle Jorge Guillén Juan C...,ATENCION ESTUDIANTES!!!! BARRIO DE VISTA ALEGR...,10 Fotos,Calle Jorge Guillén Juan Carlos I,True,DPTO. COMERCIAL PISOSMUR,<span><span>3</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>80</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
590,800 € /mes,Piso de alquiler en Santa María de Gracia,ATENCIÓN ESTUDIANTES VIVIENDA JUNTO A LA PLAZA...,9 Fotos,Santa María de Gracia,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>115</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,800 € /mes,Piso de alquiler en Santa María de Gracia,ATENCIÓN ESTUDIANTES MAGNIFICO PISOS EN SANTA ...,11 Fotos,Santa María de Gracia,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>130</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,A consultar,Piso de alquiler en Centro,FANTASTICO PISO EN AVENIDA GENERAL PRIMO DE RI...,9 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>3</span> habs.</span>,<span><span>1</span> baño</span>,NaN,...,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN
593,800 € /mes,Piso de alquiler en Calle Joselito Centro,ATENCIÓN ESTUDIANTES!!!!MAGNIFICA VIVIENDA JUN...,10 Fotos,Calle Joselito Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>100</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,A consultar,Piso de alquiler en Centro,"ESTUDIATES JUNTO A LA MERCED 4 DORMITORIOS, FA...",15 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>130</span> m²</span>,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,A consultar,Piso de alquiler en Centro,ATENCION ESTUDIANTES VIVIENDA DE 4 DORMITORIOS...,11 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,850 € /mes,Piso de alquiler en Centro,"ATENCIÓN ESTUDIANTES, MAGNIFICA VIVIENDA EN CA...",10 Fotos,Centro,True,DPTO. COMERCIAL PISOSMUR,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,NaN,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,NaN,Alquiler piso alquiler piso zona belen en Vist...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,NaN,Alquiler piso exclusiva vivienda en el Centro ...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,NaN,Alquiler dúplex estupendo triplex en alquiler ...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,NaN,Alquiler piso alquiler en juan carlos i en Vis...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,NaN,Alquiler piso de 4 habitaciones con plaza de g...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,NaN,Alquiler apartamento céntrico en El Carmen Murcia,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,NaN,"Alquiler piso estudiantes, alquiler en Vistale...",NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,NaN,Alquiler piso (zona juan de borbon) en Vistale...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,Alquiler piso estudiantes alquiler plaza juan ...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,Alquiler piso alquiler de piso en Espinardo-ju...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,NaN,Alquiler piso en calle andres sobejano se vend...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,NaN,Alquiler apartamento juan carlos i en Murcia,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,NaN,Alquiler apartamento vivienda junto cuartel de...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,NaN,Alquiler piso en barrio dEl Carmen en El Carme...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,NaN,Alquiler apartamento en plaza san nicolas en M...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,NaN,Alquiler apartamento exclusivo apto plaza flor...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,NaN,Alquiler piso alquiler de local entresuelo en ...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,NaN,"Alquiler piso en alquiler en edificio alba, sa...",NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 26

Elimina del DataFrame aquellos pisos que no tienen Precio o que su Precio sea "A consultar". Asigna el resultado a la variable fotocasa4_df:

PISTA: para seleccionar los alquileres sin precio utiliza el método isnull(). Utiliza notnull() para seleccionar los alquileres con precio..

In [27]:
fotocasa4_df = fotocasa3_df[~(fotocasa3_df['Precio'].isnull() | (fotocasa3_df['Precio'] == "A consultar"))]
# Alternativa
# fotocasa4_df = fotocasa3_df[fotocasa3_df['Precio'].notnull() & (fotocasa3_df['Precio'] != "A consultar")]
fotocasa4_df.head(3)

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Piscina,TV,Zona Deportiva,Zona Infantil,Piscina comunitaria,Serv. portería,Internet,Suite - con baño,Patio,Domótica
1,500 € /mes,Apartamento de alquiler en Centro,Maravilloso apartamento para entrar a vivir en...,21 Fotos,Centro,True,BREXTOM MURCIA,<span><span>1</span> hab.</span>,<span><span>1</span> baño</span>,<span><span>46</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,900 € /mes,Piso de alquiler en Doctor Marañón Centro,Se alquila estupenda vivienda recién reformada...,18 Fotos,Doctor Marañón Centro,True,ABAD SERVICIOS INMOBILIARIOS,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>169</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,750 € /mes,Piso de alquiler en Centro,Te presentamos este fabuloso apartamento situa...,30 Fotos,Centro,True,ABAD SERVICIOS INMOBILIARIOS,<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>77</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 27

Utiliza la función astype para convertir las columnas Tipo, Orientación, Estado y Parking a tipo categórico. Asigna los resultados a la variable fotocasa5_df y comprueba mediante el parámetro dtype que el tipo asignado sea correcto:

In [50]:
fotocasa5_df = fotocasa4_df.copy()
fotocasa5_df['Tipo'] = fotocasa5_df['Tipo'].astype("category")
fotocasa5_df['Orientación'] = fotocasa5_df['Orientación'].astype("category")
fotocasa5_df['Estado'] = fotocasa5_df['Estado'].astype("category")
fotocasa5_df['Parking'] = fotocasa5_df['Parking'].astype("category")
for column in ['Tipo', 'Orientación', 'Estado', 'Parking']:
  print(f"Tipo de columna '{column}': {fotocasa5_df[column].dtype}")
fotocasa5_df.head(3)

Tipo de columna 'Tipo': category
Tipo de columna 'Orientación': category
Tipo de columna 'Estado': category
Tipo de columna 'Parking': category

,Precio,Título,Descripción,Fotos,Dirección,Inmobiliaria,Anunciante,Habitaciones,Baños,Superficie,...,Piscina,TV,Zona Deportiva,Zona Infantil,Piscina comunitaria,Serv. portería,Internet,Suite - con baño,Patio,Domótica
1,500 € /mes,Apartamento de alquiler en Centro,Maravilloso apartamento para entrar a vivir en...,21 Fotos,Centro,True,BREXTOM MURCIA,<span><span>1</span> hab.</span>,<span><span>1</span> baño</span>,<span><span>46</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,900 € /mes,Piso de alquiler en Doctor Marañón Centro,Se alquila estupenda vivienda recién reformada...,18 Fotos,Doctor Marañón Centro,True,ABAD SERVICIOS INMOBILIARIOS,<span><span>4</span> habs.</span>,<span><span>2</span> baños</span>,<span><span>169</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,750 € /mes,Piso de alquiler en Centro,Te presentamos este fabuloso apartamento situa...,30 Fotos,Centro,True,ABAD SERVICIOS INMOBILIARIOS,<span><span>2</span> habs.</span>,<span><span>1</span> baño</span>,<span><span>77</span> m²</span>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## EJERCICIO 28

Cargar el fichero situado en https://raw.githubusercontent.com/ainaramu-icjardin/big_data/main/ciudades_ejemplo.csv
como un dataframe Pandas, y guardarlo a continuación en formato excel.

In [56]:
df = pd.read_csv("https://raw.githubusercontent.com/ainaramu-icjardin/big_data/main/ciudades_ejemplo.csv", header = 0, sep=",")
df

    ciudades  habitantes
0     Madrid     6507184
1  Barcelona     5609350
2   Valencia     2547986
3    Sevilla     1939887
4   Alicante     1838819
5     Málaga     1641121

In [57]:
df.to_excel("Datos/ciudades_ejemplo.xlsx")

## EJERCICIO 29

Cargar el fichero "https://raw.githubusercontent.com/ainaramu-icjardin/big_data/main/parocomunidades.csv" que está con codificación (encoding) "latin1" y dejarlo en un dataframe df_paro.

Mostrar solo las filas de `df_paro` que corresponden al Periodo 2019.

Mostrar solo las filas de df_paro que corresponden a un total mayor de 15.

Mostrar solo las filas que corresponden al Periodo 2019 y tienen Total mayor de 15.

In [61]:
url = "https://raw.githubusercontent.com/ainaramu-icjardin/big_data/main/parocomunidades.csv"
df_paro = pd.read_csv(url, header = 0, sep=",", encoding="latin1")
df_paro

     Comunidad  Periodo  Total
0    Andalucía     2019  20.80
1    Andalucía     2018  21.26
2    Andalucía     2017  24.43
3    Andalucía     2016  28.25
4    Andalucía     2015  29.83
..         ...      ...    ...
337    Melilla     2006   9.86
338    Melilla     2005  12.33
339    Melilla     2004  12.49
340    Melilla     2003  19.88
341    Melilla     2002   3.57

[342 rows x 3 columns]

In [63]:
filtro = df_paro["Periodo"]==2019
df_paro[filtro]

                Comunidad  Periodo  Total
0               Andalucía     2019  20.80
18                 Aragón     2019   9.93
36               Asturias     2019  13.14
54         Balears. Illes     2019   9.91
72               Canarias     2019  18.78
90              Cantabria     2019  11.18
108       Castilla y León     2019  11.20
126  Castilla - La Mancha     2019  16.56
144              Cataluña     2019  10.45
162  Comunitat Valenciana     2019  14.13
180           Extremadura     2019  23.48
198               Galicia     2019  11.74
216                Madrid     2019   9.99
234                Murcia     2019  16.08
252               Navarra     2019   9.01
270            País Vasco     2019   9.09
288              La Rioja     2019   9.89
306                 Ceuta     2019  27.58
324               Melilla     2019  26.81

In [64]:
filtro = df_paro["Total"]>=15 
df_paro[filtro]

     Comunidad  Periodo  Total
0    Andalucía     2019  20.80
1    Andalucía     2018  21.26
2    Andalucía     2017  24.43
3    Andalucía     2016  28.25
4    Andalucía     2015  29.83
..         ...      ...    ...
333    Melilla     2010  24.46
334    Melilla     2009  19.87
335    Melilla     2008  16.17
336    Melilla     2007  17.43
340    Melilla     2003  19.88

[163 rows x 3 columns]

In [65]:
filtro = (df_paro["Total"]>=15) & (df_paro["Periodo"]==2019)
df_paro[filtro]

                Comunidad  Periodo  Total
0               Andalucía     2019  20.80
72               Canarias     2019  18.78
126  Castilla - La Mancha     2019  16.56
180           Extremadura     2019  23.48
234                Murcia     2019  16.08
306                 Ceuta     2019  27.58
324               Melilla     2019  26.81